name: Portfolio CI (Quality Check)

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  build-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Starting CI
        run: echo "Portfolio CI Started.."
      
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
      
      - name: Install Dependencies
        run: npm ci

      - name: Security Audit
        run: npm audit --audit-level=high 
      
      - name: Build Project
        run: npm build
      
      # - name: Run Lint
      #   run: npm run lint